[formatter.haskell]
command = "fourmolu"
options = [
    "--ghc-opt",
    "-XImportQualifiedPost",
    "--ghc-opt",
    "-XTypeApplications",
    "--mode",
    "inplace",
    "--check-idempotence",
]
includes = ["*.hs"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

# https://github.com/srid/ema/pull/97#issuecomment-1166589918
# [formatter.cabal]
# command = "cabal-fmt"
# options = ["--inplace"]
# includes = ["*.cabal"]
