name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAINLINE: refs/heads/master
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build 🔧
        run: |
          nix build -j4 --no-link
